### ISSUE TITLE
Initial guess ignored?

### ISSUE THREAD

**Issue by Kallista** [ethz-asl/lidar_align#20]
I am providing an initial guess and setting 
`<param name="local" value="true" `
`<rosparam param="initial_guess">[1.95, 0.0, -0.7, 0.0, 0.0, 0.0, 0.0]</rosparam>`

but when the local optimization starts, what I see on the console is:
`x:   0.00 y:   0.00 z:   0.00 rx:   0.00 ry:   0.25 rz:   0.00 time:   0.00 Error:    4092.49 Iteration: 5`

Am I doing something wrong and the initial guess gets ignored or is it somehow being rejected?

**Comment by Kallista** [comment]
ah, the typo of inital vs initial

**Comment by Kallista** [comment]
Same with translation_range

**Comment by hlezki** [comment]
Hi,

Thanks for sharing the code.
Where should I set parameters (inital_guess, local, time_cal, etc.) ?? In the launch file or in a src file? Can you give some advice how can I choose best initial parameters? 

Thanks in advance.
